export const ScwAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_entryPoint", type: "address", internalType: "address" },
      { name: "_userOperationSigner", type: "address", internalType: "address" },
      { name: "_erc20Token", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "execute",
    inputs: [
      { name: "dest", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "functionData", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getEntryPoint",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getErc20Token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserOperationSigner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateUserOperationSigner",
    inputs: [{ name: "_newSigner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validateUserOp",
    inputs: [
      {
        name: "userOp",
        type: "tuple",
        internalType: "struct PackedUserOperation",
        components: [
          { name: "sender", type: "address", internalType: "address" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "initCode", type: "bytes", internalType: "bytes" },
          { name: "callData", type: "bytes", internalType: "bytes" },
          { name: "accountGasLimits", type: "bytes32", internalType: "bytes32" },
          { name: "preVerificationGas", type: "uint256", internalType: "uint256" },
          { name: "gasFees", type: "bytes32", internalType: "bytes32" },
          { name: "paymasterAndData", type: "bytes", internalType: "bytes" },
          { name: "signature", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "userOpHash", type: "bytes32", internalType: "bytes32" },
      { name: "missingAccountFunds", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "validationData", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
      { name: "newOwner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrefundPaid",
    inputs: [
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SCWExecuted",
    inputs: [
      { name: "dest", type: "address", indexed: true, internalType: "address" },
      { name: "value", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "functionData", type: "bytes", indexed: false, internalType: "bytes" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SignerUpdated",
    inputs: [
      { name: "oldSigner", type: "address", indexed: true, internalType: "address" },
      { name: "newSigner", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  { type: "error", name: "ECDSAInvalidSignature", inputs: [] },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [{ name: "length", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureS",
    inputs: [{ name: "s", type: "bytes32", internalType: "bytes32" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SCW__CallFailed",
    inputs: [{ name: "result", type: "bytes", internalType: "bytes" }],
  },
  {
    type: "error",
    name: "SCW__InvalidDestination",
    inputs: [{ name: "dest", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SCW__InvalidNonce",
    inputs: [
      { name: "currentNonce", type: "uint256", internalType: "uint256" },
      { name: "providedNonce", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "SCW__NotEnoughFunds",
    inputs: [
      { name: "currentEthBalance", type: "uint256", internalType: "uint256" },
      { name: "requiredEthBalance", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "SCW__NotFromEntryPoint", inputs: [] },
  { type: "error", name: "SCW__NotFromEntryPointOrOwner", inputs: [] },
  { type: "error", name: "SCW__ZeroAddress", inputs: [] },
] as const;
