export const ScwFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_entryPoint", type: "address", internalType: "address" },
      { name: "_erc20Token", type: "address", internalType: "address" },
      { name: "_authorizedDeployer", type: "address", internalType: "address" },
      { name: "_authorizedSigner", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "deployScw",
    inputs: [
      { name: "credentialHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAuthorizedDeployer",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAuthorizedSigner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEntryPoint",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getErc20Token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getScwAddress",
    inputs: [
      { name: "credentialHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isValidScw",
    inputs: [{ name: "scwAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "predictScwAddress",
    inputs: [
      { name: "credentialHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "sCredentialToScw",
    inputs: [
      { name: "credentialHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "scwAddress", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sIsFactoryScw",
    inputs: [{ name: "scwAddress", type: "address", internalType: "address" }],
    outputs: [{ name: "isValidScw", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateDeployer",
    inputs: [
      { name: "_newDeployer", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSigner",
    inputs: [{ name: "_newSigner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SCWDeployed",
    inputs: [
      {
        name: "credentialHash",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "scwAddress",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ScwFactory__AlreadyDeployed", inputs: [] },
  { type: "error", name: "ScwFactory__NonZeroValue", inputs: [] },
  { type: "error", name: "ScwFactory__NotAuthorizedDeployer", inputs: [] },
  { type: "error", name: "ScwFactory__zeroAddress", inputs: [] },
] as const;
